#!/usr/bin/env ansible-playbook
---
- name: Get list of Storage Arrays
  hosts: localhost
  connection: local

  vars:
    vplexhost: "10.155.201.254"
    vplexuser: "admin"
    vplexpassword: '@Pa33w0rd'
    cluster_name: "cluster-1"
    verifycert: false

  collections:
    - dellemc.vplex
  
 
  tasks:
    - name: Get list of storage arrays
      dellemc_vplex_gatherfacts:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        cluster_name: "{{ cluster_name }}"
        verifycert: "{{ verifycert }}"
        gather_subset:
          - stor_vol
        filters:
          - filter_key: use
            filter_operator: "equal"
            filter_value: "unclaimed"
      register: array_extents
    - debug:
        var: array_extents