---
  - hosts: nfs
    become: true
    vars:
      share_path : "/mnt/nfsroot"
    tasks:
      - name: make sure nfs-util is installed
        package:
          name: nfs-utils
          state: latest
      - name: start and enable nfs-server
        service:
          name: nfs-server
          state: started
          enabled: yes

      - name: deploy ansible exports template
        template:
          src: /home/ansible/exports.j2
          dest: /etc/exports
        notify: run exportfs

  - hosts: remote
    become: true
    vars:
      nfs_ip: "{{ hostvars['nfs']['ansible_default_ipv4']['address'] }}"
      nfs_hostname: "{{ hostvars['nfs']['ansible_hostname'] }}"
    vars_files:
      - /home/ansible/user-list.txt
    tasks:
      - name: copy etc.hosts template to /etc/hosts
        template:
          src: /home/ansible/etc.hosts.j2
          dest: /etc/hosts
      - name: get file status
        stat:
          path: /opt/user-agreement.txt
        register: filestat
      - name: debug info
        debug:
          var: filestat
      - name: create users
        user:
          name: "{{ item }}"
        when:  filestat.stat.exists
        loop: "{{ users }}"




    handlers:
      - name: run exportfs
        shell: "exportfs -a"
