- hosts: all
  tasks:
  - name: copy public access key to remote servers
    authorized_key:
      key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
      user: "{{ ansible_user_id }}"
      state: present