---
- name: collect default set of information
  hosts: localhost
  connection: local
  collections:
    - purestorage.flasharray
  
  tasks:
  - name: show default info
    purefa_info:
      fa_url: 10.155.201.217
      api_token: 69f2c5fe-d588-76a0-e07b-0566e5da3e18
    register: array_info

  - debug:
      msg: "{{ array_info['purefa_info']['default'] }}"