---
- name: Remove virtual volume playbook
  hosts: localhost
  connection: local
  vars_files:
    - ~/ansible/vplex_playbooks/Remove_storage/var.yml
    - ~/ansible/vplex_playbooks/credentials.yml

  vars:
    input: &vplex_connection_vars
      vplexhost: "{{ vplexhost }}"
      vplexuser: "{{ vplexuser }}"
      vplexpassword: "{{ vplexpassword }}"
      verifycert: "{{ verifycert }}"
      cluster_name: "{{ cluster_name }}"
      #volume_id: "{{ volume_id }}"

  collections:
    - dellemc.vplex
  
  tasks:
    # - name: Get storage view details
    #   dellemc_vplex_storage_view:
    #     <<: *vplex_connection_vars
    #     storage_view_name: "VHCCFSQL2"
    #     state: "present"
    #   register: storage_view_info
    
    # - debug: 
    #     var: (storage_view_info.storageview_details.virtual_volumes | map(attribute='uri'))
    
    # - local_action: lineinfile line={{ storage_view_info.storageview_details.virtual_volumes | map(attribute='uri') }} path=./storage_view_info.txt

    - name: Get map for virtual volume
      dellemc_vplex_maps:
        <<: *vplex_connection_vars
        entity_type: 'virtual_volumes'
        entity_name: "{{item}}"
      loop: "{{ volume_names }}"
      register: vv_map
    
    - local_action: lineinfile line={{ vv_map }} path=./vv_map.txt


    
    # - name: Delete virtual volume using name
    #   dellemc_vplex_virtual_volume:
    #     virtual_volume_name: "{{ item }}"
    #     state: "absent"
    #   loop: "{{ volume_names }}"
