---
- name: Remove virtual volume playbook
  hosts: localhost
  connection: local
  vars_files:
    - ~/ansible/vplex_playbooks/Remove_storage/var.yml
    - ~/ansible/vplex_playbooks/credentials.yml

  vars:
    input: &vplex_connection_vars
      vplexhost: "{{ vplexhost }}"
      vplexuser: "{{ vplexuser }}"
      vplexpassword: "{{ vplexpassword }}"
      verifycert: "{{ verifycert }}"
      cluster_name: "{{ cluster_name }}"

  collections:
    - dellemc.vplex
  
  tasks:
    - name: Unclaim Storage Volume
      dellemc_vplex_storage_volume:
        <<: *vplex_connection_vars
        storage_volume_name: "{{ item }}"
        claimed_state: unclaimed
        state: present
      loop: "{{ Storage_volumes }}"