---
  - hosts: ubuntu
    vars:
      - devops_password: '$6$.BD0QlnnF$8dR/GcLuA7G6rL4T3jKehergFKILljq4xWAbdRDndO.cBIaCHcu4zR71NDGGrdoe3SVnY9B2XGKgYhD66Ww1N.'
    gather_facts: no
    #remote_user: sshastry
    become: true
    tasks:
    - name: Add a new user named ansible
      user:
        name: ansible
        shell: /bin/bash
        password: "{{ devops_password }}"
      
    - name: Add ansible user to the sudoers
      copy:
        dest: "/etc/sudoers.d/ansible"
        content: "ansible  ALL=(ALL)  NOPASSWD: ALL"

    - name: Deploy SSH Key
      authorized_key: 
        user=ansible
        key="{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
        state=present
  
    - name: Disable Password Authentication
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PasswordAuthentication'
        line="PasswordAuthentication yes"
        state=present
        backup=yes

    - name: Disable Root Login
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PermitRootLogin'
        line="PermitRootLogin yes"
        state=present
        backup=yes
      notify:
      - restart ssh

    handlers:
      - name: restart ssh
        service:
          name=sshd
          state=restarted